code = (
    "import 'package:flutter/material.dart';\n"
    "import 'services/api_service.dart';\n"
    "import 'screens/login_screen.dart';\n"
    "import 'screens/home_screen.dart';\n"
    "\n"
    "void main() {\n"
    "  runApp(const DolapApp());\n"
    "}\n"
    "\n"
    "class DolapApp extends StatelessWidget {\n"
    "  const DolapApp({super.key});\n"
    "  @override\n"
    "  Widget build(BuildContext context) {\n"
    "    return MaterialApp(\n"
    "      title: 'Dolap',\n"
    "      debugShowCheckedModeBanner: false,\n"
    "      theme: ThemeData(useMaterial3: true),\n"
    "      home: const SplashRouter(),\n"
    "    );\n"
    "  }\n"
    "}\n"
    "\n"
    "class SplashRouter extends StatefulWidget {\n"
    "  const SplashRouter({super.key});\n"
    "  @override\n"
    "  State<SplashRouter> createState() => _SplashRouterState();\n"
    "}\n"
    "\n"
    "class _SplashRouterState extends State<SplashRouter> {\n"
    "  @override\n"
    "  void initState() {\n"
    "    super.initState();\n"
    "    _checkAuth();\n"
    "  }\n"
    "\n"
    "  Future<void> _checkAuth() async {\n"
    "    final token = await ApiService.getToken();\n"
    "    if (!mounted) return;\n"
    "    Navigator.pushReplacement(\n"
    "      context,\n"
    "      MaterialPageRoute(\n"
    "        builder: (_) =>\n"
    "            token != null ? const HomeScreen() : const LoginScreen(),\n"
    "      ),\n"
    "    );\n"
    "  }\n"
    "\n"
    "  @override\n"
    "  Widget build(BuildContext context) {\n"
    "    return const Scaffold(\n"
    "      backgroundColor: Color(0xFFF8F4F0),\n"
    "      body: Center(\n"
    "        child: Column(\n"
    "          mainAxisAlignment: MainAxisAlignment.center,\n"
    "          children: [\n"
    "            Icon(Icons.checkroom, size: 60, color: Color(0xFF2D2D2D)),\n"
    "            SizedBox(height: 16),\n"
    "            Text(\n"
    "              'Dolap',\n"
    "              style: TextStyle(\n"
    "                fontSize: 28,\n"
    "                fontWeight: FontWeight.bold,\n"
    "                color: Color(0xFF2D2D2D),\n"
    "              ),\n"
    "            ),\n"
    "          ],\n"
    "        ),\n"
    "      ),\n"
    "    );\n"
    "  }\n"
    "}\n"
)

with open('/Users/busenurakdeniz/dolap_app/lib/main.dart', 'w') as f:
    f.write(code)

print('main.dart yazildi!')
